const palette = {
  coral: "#FF6B6B",
  coralLight: "#FF8A8A",
  teal: "#2EC4B6",
  tealLight: "#4DD9CC",
  navy: "#1A1A2E",
  navyLight: "#16213E",
  darkCard: "#222244",
  darkSurface: "#2A2A4A",
  white: "#FFFFFF",
  offWhite: "#F8F9FA",
  gray100: "#F1F3F5",
  gray200: "#E9ECEF",
  gray300: "#DEE2E6",
  gray400: "#ADB5BD",
  gray500: "#6C757D",
  gray600: "#495057",
  gray700: "#343A40",
  gold: "#FFD93D",
  green: "#51CF66",
};

const Colors = {
  light: {
    text: palette.gray700,
    textSecondary: palette.gray500,
    background: palette.offWhite,
    card: palette.white,
    tint: palette.coral,
    tintSecondary: palette.teal,
    tabIconDefault: palette.gray400,
    tabIconSelected: palette.coral,
    border: palette.gray200,
    playerA: palette.coral,
    playerALight: palette.coralLight,
    playerB: palette.teal,
    playerBLight: palette.tealLight,
    gold: palette.gold,
    success: palette.green,
    surface: palette.gray100,
  },
  dark: {
    text: palette.white,
    textSecondary: palette.gray400,
    background: palette.navy,
    card: palette.darkCard,
    tint: palette.coral,
    tintSecondary: palette.teal,
    tabIconDefault: palette.gray500,
    tabIconSelected: palette.coral,
    border: palette.darkSurface,
    playerA: palette.coral,
    playerALight: palette.coralLight,
    playerB: palette.teal,
    playerBLight: palette.tealLight,
    gold: palette.gold,
    success: palette.green,
    surface: palette.darkSurface,
  },
};

export default Colors;
